- job:
    name: designate-devstack-base
    parent: legacy-dsvm-base
    vars:
      database: mysql
      python_version: py27
      identity_v3_only: 0
      manager_model: 0
      backend: pdns4
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
      - openstack/tempest
    run: playbooks/legacy/designate-devstack-base/run.yaml
    post-run: playbooks/legacy/designate-devstack-base/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$

- job:
    name: designate-devstack-agent-base
    parent: legacy-dsvm-base
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
      - openstack/tempest
    run: playbooks/legacy/designate-devstack-agent-base/run.yaml
    post-run: playbooks/legacy/designate-devstack-agent-base/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$

- job:
    name: grenade-devstack-designate-pdns4
    parent: legacy-dsvm-base
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
    run: playbooks/legacy/grenade-devstack-designate-pdns4/run.yaml
    post-run: playbooks/legacy/grenade-devstack-designate-pdns4/post.yaml
    timeout: 10800

- job:
    name: designate-devstack-agent-djbdns
    parent: designate-devstack-agent-base
    vars:
      backend_driver: djbdns

- job:
    name: designate-devstack-agent-gdnsd
    parent: designate-devstack-agent-base
    vars:
      backend_driver: gdnsd

- job:
    name: designate-devstack-agent-knot2
    parent: designate-devstack-agent-base
    vars:
      backend_driver: knot2

- job:
    name: designate-devstack-bind9
    parent: designate-devstack-base
    vars:
      backend: bind9

- job:
    name: designate-devstack-pdns4
    parent: designate-devstack-base
    vars:
      backend: pdns4

- job:
    name: designate-devstack-pdns4-postgres
    parent: designate-devstack-base
    vars:
      backend: pdns4
      database: postgres

- job:
    name: designate-devstack-pdns4-py35
    parent: designate-devstack-base
    vars:
      backend: pdns4
      python_version: py35

- job:
    name: designate-devstack-pdns4-manager-model
    parent: designate-devstack-base
    vars:
      manager_model: 1

- project-template:
    name: designate-devstack-jobs
    check:
      jobs:
        - designate-devstack-bind9
        - designate-devstack-pdns4
        - designate-devstack-pdns4-postgres
        - designate-devstack-pdns4-manager-model
        - designate-devstack-pdns4-py35
        - grenade-devstack-designate-pdns4
    gate:
      queue: designate
      jobs:
        - designate-devstack-bind9
        - designate-devstack-pdns4
        - designate-devstack-pdns4-postgres
        - designate-devstack-pdns4-manager-model
        - grenade-devstack-designate-pdns4
    experimental:
      jobs:
        - designate-devstack-agent-knot2
        - designate-devstack-agent-djbdns
        - designate-devstack-agent-gdnsd

- project:
    templates:
      - designate-devstack-jobs
    check:
      jobs:
        - neutron-tempest-plugin-designate-scenario:
            voting: false
        - requirements-check:
            voting: false
    gate:
      jobs:
        - neutron-tempest-plugin-designate-scenario:
            voting: false
        - requirements-check:
            voting: false
