- job:
    name: designate-base
    parent: devstack-tempest
    vars:
      devstack_localrc:
        DESIGNATE_SERVICE_PORT_DNS: 5322
        TEMPEST_PLUGINS: /opt/stack/designate-tempest-plugin
        USE_PYTHON3: true
      devstack_plugins:
        designate: https://opendev.org/openstack/designate
      devstack_services:
        designate: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-bak: false
      tox_envlist: all-plugin
      tempest_test_regex: |
        designate_tempest_plugin.*
    required-projects:
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$

- job:
    name: designate-bind9
    post-run: playbooks/designate-bind9/post.yaml
    parent: designate-base

- job:
    name: designate-pdns4
    post-run: playbooks/designate-pdns4/post.yaml
    parent: designate-base
    vars:
      devstack_localrc:
        DESIGNATE_BACKEND_DRIVER: pdns4

- job:
    name: designate-pdns4-postgres
    parent: designate-pdns4
    vars:
      database: postgres

- job:
    name: designate-bind9-manager-model
    parent: designate-bind9
    vars:
      devstack_services:
        designate-worker: false
        designate-producer: false
        designate-pool-manager: true
        designate-zone-manager: true

- job:
    name: designate-bind9-py27
    parent: designate-bind9
    vars:
      devstack_localrc:
        USE_PYTHON3: false
      devstack_services:
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
        c-bak: true


- job:
    name: designate-pdns4-py27
    parent: designate-pdns4
    vars:
      devstack_localrc:
        USE_PYTHON3: false
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-bak: false

- job:
    name: designate-grenade-pdns4
    parent: legacy-dsvm-base
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
      - openstack/python-designateclient
    run: playbooks/legacy/grenade-devstack-designate-pdns4/run.yaml
    post-run: playbooks/legacy/grenade-devstack-designate-pdns4/post.yaml
    timeout: 10800
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$

- project-template:
    name: designate-devstack-jobs
    check:
      jobs:
        - designate-bind9
        - designate-pdns4
        - designate-bind9-manager-model
        - designate-bind9-py27
        - designate-pdns4-py27
        - designate-pdns4-postgres
        - designate-grenade-pdns4
    gate:
      queue: designate
      jobs:
        - designate-bind9
        - designate-pdns4
        - designate-bind9-manager-model
        - designate-bind9-py27
        - designate-pdns4-py27
        - designate-pdns4-postgres
        - designate-grenade-pdns4

- project:
    templates:
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-tempest-plugin-designate-scenario
    gate:
      queue: designate
